const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])), money=n=>'R '+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const seed={settings:{bizName:'',bizVat:'',bizEmail:'',bizPhone:'',bizAddress:'',bankHolder:'',bank:'',bankAccount:'',bankBranch:'',invPrefix:'INV-',quotePrefix:'QUO-',vatRate:0,thanks:'Thank You For Your Booking'},shows:[],clients:[],quotes:[],invoices:[],marketing:[],contracts:[],activity:[]};
let db=JSON.parse(localStorage.getItem('showpay_db')||'null')||structuredClone(seed), page='home', cal=new Date(), editing=null;
function save(){localStorage.setItem('showpay_db',JSON.stringify(db));render();}
function toast(t){let x=$('#toast');x.textContent=t;x.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.style.display='none',2200)}
function next(type){let arr=db[type+'s'];let prefix=type==='invoice'?db.settings.invPrefix||'INV-':db.settings.quotePrefix||'QUO-';let max=arr.reduce((m,x)=>Math.max(m,parseInt(String(x.number||'').replace(/\D/g,''))||0),0);return prefix+String(max+1).padStart(4,'0')}
function nav(p){page=p;render();requestAnimationFrame(()=>{window.scrollTo({top:0,left:0,behavior:'instant'});document.documentElement.scrollTop=0;document.body.scrollTop=0;const m=$('#main');if(m)m.focus({preventScroll:true});});}
function render(){document.querySelectorAll('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===page));let m=$('#main');m.innerHTML=views[page]?views[page]():views.home();}
function shell(title,sub,action=''){return `<div class="section-head"><div><h2>${title}</h2><p>${sub||''}</p></div>${action}</div>`}
const views={
home(){let paid=db.invoices.filter(i=>i.status==='Paid').reduce((a,i)=>a+i.total,0),due=db.invoices.filter(i=>i.status!=='Paid').reduce((a,i)=>a+i.total,0);return `<section class="hero"><img src="${window.SHOWPAY_MASTER_ARTWORK}" alt="ShowPay master artwork"><div class="hero-content"><div class="eyebrow">Artist Business Management</div><h1>ShowPay</h1><p>Your shows, clients, quotes, invoices, income, marketing and contracts — in one artist desk.</p><div class="hero-actions"><button class="btn gold" data-action="quickShow">＋ Add Show</button><button class="btn" data-action="quickInvoice">＋ New Invoice</button><button class="btn" data-action="quickQuote">＋ New Quote</button></div></div></section><div class="grid stats"><div class="card stat"><small>Upcoming Shows</small><strong>${db.shows.filter(s=>s.date>=today()).length}</strong></div><div class="card stat"><small>Clients</small><strong>${db.clients.length}</strong></div><div class="card stat"><small>Paid Income</small><strong>${money(paid)}</strong></div><div class="card stat"><small>Outstanding</small><strong>${money(due)}</strong></div></div>${shell('Recent Activity','Latest ShowPay activity')}<div class="list">${db.activity.slice(0,8).map(x=>`<div class="item"><div><b>${esc(x)}</b><small>ShowPay</small></div></div>`).join('')||'<div class="empty">Your activity will appear here.</div>'}</div>`},
shows(){return `${shell('Shows','Manage bookings, venues, fees and ownership.','<button class="btn gold" data-action="quickShow">＋ Add Show</button>')}<div class="list">${db.shows.map(s=>`<div class="item"><div><b>${esc(s.title)}</b><small>${esc(s.date)} · ${esc(s.venue)} · ${esc(s.owner||'Shared')}</small></div><div><strong>${money(s.fee)}</strong><div class="actions"><button class="tiny" data-edit-show="${s.id}">Edit</button><button class="tiny" data-delete-show="${s.id}">Delete</button></div></div></div>`).join('')||'<div class="empty">No shows yet.</div>'}</div>`},
calendar(){let y=cal.getFullYear(),m=cal.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),cells='';for(let i=0;i<first;i++)cells+='<div></div>';for(let d=1;d<=days;d++){let iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;cells+=`<div><b>${d}</b>${db.shows.filter(s=>s.date===iso).map(s=>`<div class="event ${s.owner==='Fiancé'?'partner':s.owner==='You'?'you':'shared'}">${esc(s.title)}</div>`).join('')}</div>`}return `${shell('Calendar','TimeTree-style monthly booking calendar.','<button class="btn gold" data-action="quickShow">＋ Add Show</button>')}<div class="card calendar"><div class="cal-toolbar"><button class="tiny" data-action="prevMonth">←</button><b>${cal.toLocaleString('en-ZA',{month:'long',year:'numeric'})}</b><button class="tiny" data-action="nextMonth">→</button></div><div class="cal-grid">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div class="dow">${x}</div>`).join('')}${cells}</div></div>`},
clients(){return `${shell('Clients','Your artist/client database.','<button class="btn gold" data-action="quickClient">＋ Add Client</button>')}<div class="list">${db.clients.map(c=>`<div class="item"><div><b>${esc(c.name)}</b><small>${esc(c.phone)} · ${esc(c.email)}<br>${esc(c.address)}${c.vat?'<br>VAT: '+esc(c.vat):''}</small></div><div class="actions"><button class="tiny" data-edit-client="${c.id}">Edit</button><button class="tiny" data-delete-client="${c.id}">Delete</button></div></div>`).join('')||'<div class="empty">No clients yet.</div>'}</div>`},
quotes(){return `${shell('Quotes','Create, edit, print and convert quotes to invoices.','<button class="btn gold" data-action="quickQuote">＋ New Quote</button>')}<div class="list">${db.quotes.map(q=>docRow(q,'quote')).join('')||'<div class="empty">No quotes yet.</div>'}</div>`},
invoices(){return `${shell('Invoices','Create invoices, mark them paid, print A4 PDFs and share.','<button class="btn gold" data-action="quickInvoice">＋ New Invoice</button>')}<div class="list">${db.invoices.map(i=>docRow(i,'invoice')).join('')||'<div class="empty">No invoices yet.</div>'}</div>`},
income(){let paid=db.invoices.filter(i=>i.status==='Paid'),total=paid.reduce((a,i)=>a+i.total,0);return `${shell('Income','Paid invoices and recorded revenue.')}<div class="grid stats"><div class="card stat"><small>Total Paid</small><strong>${money(total)}</strong></div><div class="card stat"><small>Paid Invoices</small><strong>${paid.length}</strong></div></div><div class="list" style="margin-top:14px">${paid.map(i=>`<div class="item"><div><b>${esc(i.number)}</b><small>${esc(clientName(i.clientId))} · ${i.paidDate||''}</small></div><strong>${money(i.total)}</strong></div>`).join('')||'<div class="empty">No paid invoices yet.</div>'}</div>`},
reports(){let revenue=db.invoices.filter(i=>i.status==='Paid').reduce((a,i)=>a+i.total,0),quoted=db.quotes.reduce((a,i)=>a+i.total,0),out=db.invoices.filter(i=>i.status!=='Paid').reduce((a,i)=>a+i.total,0);return `${shell('Reports','A simple business snapshot.')}<div class="grid three"><div class="card"><small>Paid Revenue</small><h2>${money(revenue)}</h2></div><div class="card"><small>Quoted Value</small><h2>${money(quoted)}</h2></div><div class="card"><small>Outstanding</small><h2>${money(out)}</h2></div></div><div class="card" style="margin-top:14px"><table class="table"><tr><th>Metric</th><th>Value</th></tr><tr><td>Shows</td><td>${db.shows.length}</td></tr><tr><td>Clients</td><td>${db.clients.length}</td></tr><tr><td>Quotes</td><td>${db.quotes.length}</td></tr><tr><td>Invoices</td><td>${db.invoices.length}</td></tr></table></div>`},
marketing(){return `${shell('Marketing','Plan campaigns and posting activity.','<button class="btn gold" data-action="quickMarketing">＋ Add Campaign</button>')}<div class="list">${db.marketing.map((x,i)=>`<div class="item"><div><b>📱 ${esc(x.name)}</b><small>${esc(x.date)} · ${esc(x.channel)} · ${esc(x.status||'Planned')}</small></div><button class="tiny" data-delete-marketing="${i}">Delete</button></div>`).join('')||'<div class="empty">No campaigns yet.</div>'}</div><div class="card" style="margin-top:14px"><b>Smart posting note</b><p class="note">ShowPay can store planned posting times, channels and hashtags. Actual automatic posting and platform algorithm access require the relevant social-media APIs and permissions.</p></div>`},
contracts(){return `${shell('Contracts','Booking agreements and contract records.','<button class="btn gold" data-action="quickContract">＋ Add Contract</button>')}<div class="list">${db.contracts.map((x,i)=>`<div class="item"><div><b>📄 ${esc(x.name)}</b><small>${esc(x.client)} · ${esc(x.date)} · ${esc(x.status||'Draft')}</small></div><button class="tiny" data-delete-contract="${i}">Delete</button></div>`).join('')||'<div class="empty">No contracts yet.</div>'}</div>`},
settings(){let s=db.settings;return `${shell('Settings','Artist/business details used on documents.')}<div class="cover"><div class="card"><h3>Business / Artist</h3><div class="form-grid"><div class="field full"><label>Name</label><input id="sName" value="${esc(s.bizName)}"></div><div class="field"><label>VAT number</label><input id="sVat" value="${esc(s.bizVat)}"></div><div class="field"><label>Email</label><input id="sEmail" value="${esc(s.bizEmail)}"></div><div class="field"><label>Phone</label><input id="sPhone" value="${esc(s.bizPhone)}"></div><div class="field full"><label>Business address</label><textarea id="sAddress">${esc(s.bizAddress)}</textarea></div></div></div><div class="card"><h3>Bank & Invoice</h3><div class="form-grid"><div class="field"><label>Account holder</label><input id="sHolder" value="${esc(s.bankHolder)}"></div><div class="field"><label>Bank</label><input id="sBank" value="${esc(s.bank)}"></div><div class="field"><label>Account number</label><input id="sAccount" value="${esc(s.bankAccount)}"></div><div class="field"><label>Branch code</label><input id="sBranch" value="${esc(s.bankBranch)}"></div><div class="field"><label>Invoice prefix</label><input id="sInvPrefix" value="${esc(s.invPrefix)}"></div><div class="field"><label>Quote prefix</label><input id="sQuotePrefix" value="${esc(s.quotePrefix)}"></div><div class="field"><label>Default VAT %</label><input id="sVatRate" type="number" value="${Number(s.vatRate||0)}"></div><div class="field full"><label>Thank-you message</label><input id="sThanks" value="${esc(s.thanks)}"></div></div></div></div><button class="btn gold" style="margin-top:14px" data-action="saveSettings">Save Settings</button>`},
more(){return `${shell('More','More ShowPay tools and settings.')}<div class="grid two"><button class="card nav-card" data-go="invoices"><b>🧾 Invoices</b><small>Manage invoices and payments</small></button><button class="card nav-card" data-go="quotes"><b>📝 Quotes</b><small>Create and convert quotes</small></button><button class="card nav-card" data-go="income"><b>💰 Income</b><small>View paid income</small></button><button class="card nav-card" data-go="reports"><b>📊 Reports</b><small>Business overview</small></button><button class="card nav-card" data-go="marketing"><b>📱 Marketing</b><small>Campaign planning</small></button><button class="card nav-card" data-go="contracts"><b>📄 Contracts</b><small>Contract records</small></button><button class="card nav-card" data-go="settings"><b>⚙️ Settings</b><small>Business and bank details</small></button></div>`}
};


function marketingForm(){openModal(`<h2>Add Campaign</h2><div class="form-grid"><div class="field full"><label>Campaign / Post</label><input id="mName"></div><div class="field"><label>Date</label><input id="mDate" type="date" value="${today()}"></div><div class="field"><label>Channel</label><input id="mChannel" placeholder="Facebook / Instagram / TikTok"></div><div class="field"><label>Status</label><select id="mStatus"><option>Planned</option><option>Scheduled</option><option>Posted</option></select></div></div><button class="btn gold" data-save-marketing>Save Campaign</button>`)}
function contractForm(){openModal(`<h2>Add Contract</h2><div class="form-grid"><div class="field full"><label>Contract / Booking</label><input id="ctName"></div><div class="field"><label>Client</label><input id="ctClient"></div><div class="field"><label>Date</label><input id="ctDate" type="date" value="${today()}"></div><div class="field"><label>Status</label><select id="ctStatus"><option>Draft</option><option>Sent</option><option>Signed</option></select></div></div><button class="btn gold" data-save-contract>Save Contract</button>`)}

function clientName(id){return db.clients.find(c=>c.id===id)?.name||'Client not selected'}
function docRow(d,type){return `<div class="item"><div><b>${esc(d.number)}</b><small>${esc(clientName(d.clientId))} · ${esc(d.date)} · ${type==='invoice'?d.status:''}</small></div><div><strong>${money(d.total)}</strong>${type==='invoice'?`<span class="status ${d.status==='Paid'?'paid':'unpaid'}">${d.status}</span>`:''}<div class="actions"><button class="tiny" data-edit-doc="${type}:${d.id}">Edit</button>${type==='quote'?`<button class="tiny" data-convert="${d.id}">Invoice</button>`:''}${type==='invoice'&&d.status!=='Paid'?`<button class="tiny" data-paid="${d.id}">Paid</button>`:''}<button class="tiny" data-print-doc="${type}:${d.id}">A4 PDF</button><button class="tiny" data-whats="${type}:${d.id}">WhatsApp</button><button class="tiny" data-delete-doc="${type}:${d.id}">Delete</button></div></div></div>`}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').hidden=false}function closeModal(){$('#modal').hidden=true;editing=null}
function clientOptions(selected=''){return '<option value="">Select client</option>'+db.clients.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${esc(c.name)}</option>`).join('')}
function showForm(id=''){let s=id?db.shows.find(x=>x.id===id):null;openModal(`<h2>${s?'Edit':'Add'} Show</h2><div class="form-grid"><div class="field full"><label>Show name</label><input id="fTitle" value="${esc(s?.title||'')}"></div><div class="field"><label>Date</label><input id="fDate" type="date" value="${s?.date||today()}"></div><div class="field"><label>Venue</label><input id="fVenue" value="${esc(s?.venue||'')}"></div><div class="field"><label>Fee (R)</label><input id="fFee" type="number" step="0.01" value="${s?.fee||0}"></div><div class="field"><label>Owner</label><select id="fOwner"><option>You</option><option>Fiancé</option><option>Shared</option></select></div></div><button class="btn gold" data-save-show="${id}">Save Show</button>`)}
function clientForm(id=''){let c=id?db.clients.find(x=>x.id===id):null;openModal(`<h2>${c?'Edit':'Add'} Client</h2><div class="form-grid"><div class="field full"><label>Client / Business Name</label><input id="cName" value="${esc(c?.name||'')}"></div><div class="field"><label>VAT number</label><input id="cVat" value="${esc(c?.vat||'')}"></div><div class="field"><label>Phone</label><input id="cPhone" value="${esc(c?.phone||'')}"></div><div class="field"><label>Email</label><input id="cEmail" value="${esc(c?.email||'')}"></div><div class="field full"><label>Address</label><textarea id="cAddress">${esc(c?.address||'')}</textarea></div></div><button class="btn gold" data-save-client="${id}">Save Client</button>`)}
function docForm(type,id=''){let d=id?db[type+'s'].find(x=>x.id===id):null;d=d||{number:next(type),reference:'',date:today(),due:today(),eventDate:'',terms:'',sales:'',job:'',clientId:'',vatRate:Number(db.settings.vatRate||0),thanks:db.settings.thanks||'Thank You For Your Booking',items:[{qty:1,desc:'',price:0}]};openModal(`<h2>${id?'Edit':'New'} ${type==='invoice'?'Invoice':'Quote'}</h2><div class="form-grid"><div class="field"><label>${type==='invoice'?'Invoice':'Quote'} number</label><input id="dNumber" value="${esc(d.number)}"></div><div class="field"><label>Reference</label><input id="dReference" value="${esc(d.reference)}"></div><div class="field"><label>Date</label><input id="dDate" type="date" value="${d.date||today()}"></div><div class="field"><label>Due Date</label><input id="dDue" type="date" value="${d.due||today()}"></div><div class="field"><label>Date Of Event</label><input id="dEvent" type="date" value="${d.eventDate||''}"></div><div class="field"><label>Client</label><select id="dClient">${clientOptions(d.clientId)}</select></div><div class="field"><label>Payment Terms</label><input id="dTerms" value="${esc(d.terms)}"></div><div class="field"><label>Client VAT / Sales Tax</label><input id="dSales" value="${esc(d.sales)}"></div><div class="field full"><label>Job / Event description</label><input id="dJob" value="${esc(d.job)}"></div></div><div class="section-head"><div><h3>Line Items</h3></div><button class="tiny gold" data-add-line>Add Line</button></div><div id="lines" class="lines">${d.items.map(lineHtml).join('')}</div><div class="field" style="max-width:160px"><label>VAT %</label><input id="dVat" type="number" step="0.01" value="${Number(d.vatRate||0)}"></div><div class="doc-total"><div>Subtotal <b id="sub">R 0.00</b></div><div>VAT <b id="vat">R 0.00</b></div><div class="grand">Total <b id="total">R 0.00</b></div></div><div class="field full"><label>Thank You For Your Booking</label><input id="dThanks" value="${esc(d.thanks)}"></div><button class="btn gold" data-save-doc="${type}:${id}">Save ${type}</button>`);recalc()}
function lineHtml(v={qty:1,desc:'',price:0}){return `<div class="line"><input class="qty" type="number" step="0.01" value="${v.qty}"><input class="desc" placeholder="Description" value="${esc(v.desc)}"><input class="price" type="number" step="0.01" value="${v.price}"><button class="tiny" data-remove-line>×</button></div>`}
function recalc(){let sub=[...document.querySelectorAll('#lines .line')].reduce((a,r)=>a+Number(r.querySelector('.qty').value||0)*Number(r.querySelector('.price').value||0),0),vat=sub*Number($('#dVat')?.value||0)/100;$('#sub').textContent=money(sub);$('#vat').textContent=money(vat);$('#total').textContent=money(sub+vat);return{sub,vat,total:sub+vat}}
function saveDoc(type,id){let x=recalc(),o={id:id||uid(),number:$('#dNumber').value,reference:$('#dReference').value,date:$('#dDate').value,due:$('#dDue').value,eventDate:$('#dEvent').value,terms:$('#dTerms').value,sales:$('#dSales').value,job:$('#dJob').value,clientId:$('#dClient').value,subtotal:x.sub,vat:x.vat,vatRate:Number($('#dVat').value||0),total:x.total,thanks:$('#dThanks').value,status:id?(db[type+'s'].find(a=>a.id===id)?.status||'Unpaid'):'Unpaid',items:[...document.querySelectorAll('#lines .line')].map(r=>({qty:+r.querySelector('.qty').value,desc:r.querySelector('.desc').value,price:+r.querySelector('.price').value}))};let arr=db[type+'s'],i=arr.findIndex(a=>a.id===o.id);i>=0?arr[i]=o:arr.push(o);db.activity.unshift(`${o.number} saved`);save();closeModal();toast(`${o.number} saved`)}
function printDoc(type,id){let d=db[type+'s'].find(x=>x.id===id),c=db.clients.find(x=>x.id===d.clientId),s=db.settings;let rows=d.items.map(i=>`<tr><td>${i.qty}</td><td>${esc(i.desc)}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join('');let w=open('','_blank');if(!w){toast('Allow pop-ups for PDF printing');return}w.document.write(`<!doctype html><html><head><title>${esc(d.number)}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial;color:#111;font-size:10pt}.head{display:flex;justify-content:space-between}.right{text-align:right}h1{margin:0 0 10px}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{border:1px solid #222;padding:8px;text-align:left}.num{text-align:right}.bank{margin-top:28px}hr{border:0;border-top:1px solid #999;margin:18px 0}</style></head><body><div class=head><div><h2>${esc(s.bizName||'Artist')}</h2>${esc(s.bizAddress||'').replace(/\n/g,'<br>')}<br>${esc(s.bizEmail||'')}<br>${esc(s.bizPhone||'')}</div><div class=right><h1>${type.toUpperCase()}</h1><b>Number:</b> ${esc(d.number)}<br><b>Reference:</b> ${esc(d.reference)}<br><b>Date:</b> ${esc(d.date)}<br><b>Due Date:</b> ${esc(d.due)}</div></div><hr><div class=head><div><b>TO</b><br>${esc(c?.name||'')}<br>${esc(c?.address||'').replace(/\n/g,'<br>')}<br>VAT: ${esc(c?.vat||'')}</div><div class=right><b>Date Of Event</b><br>${esc(d.eventDate||'')}</div></div><table><tr><th>Qty</th><th>Description</th><th>Unit Price</th><th>Line Total</th></tr>${rows}</table><div class=num style="margin-top:14px">Subtotal: ${money(d.subtotal)}<br>VAT: ${money(d.vat)}<br><strong>Total: ${money(d.total)}</strong></div><div class=bank><b>Bank Details</b><br>${esc(s.bankHolder||'')}<br>${esc(s.bank||'')}<br>Account: ${esc(s.bankAccount||'')}<br>Branch: ${esc(s.bankBranch||'')}</div><p style="text-align:center;margin-top:45px"><i>${esc(d.thanks||'Thank You For Your Booking')}</i></p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='showpay-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
function importData(){$('#importFile').click()}
function quickPrompt(title,fields,cb){let html=`<h2>${title}</h2><div class="form-grid">${fields.map(f=>`<div class="field ${f.full?'full':''}"><label>${f.label}</label><input id="q_${f.id}" type="${f.type||'text'}" value="${esc(f.value||'')}"></div>`).join('')}</div><button class="btn gold" id="quickSave">Save</button>`;openModal(html);$('#quickSave').onclick=()=>{let o={};fields.forEach(f=>o[f.id]=$('#q_'+f.id).value);cb(o);closeModal();save()}}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.go)nav(b.dataset.go);if(b.dataset.action==='closeModal')closeModal();if(b.dataset.action==='quickShow')showForm();if(b.dataset.action==='quickClient')clientForm();if(b.dataset.action==='quickQuote')docForm('quote');if(b.dataset.action==='quickInvoice')docForm('invoice');if(b.dataset.action==='quickMarketing')marketingForm();if(b.dataset.action==='quickContract')contractForm();if(b.dataset.action==='prevMonth'){cal.setMonth(cal.getMonth()-1);render()}if(b.dataset.action==='nextMonth'){cal.setMonth(cal.getMonth()+1);render()}if(b.dataset.action==='exportData')exportData();if(b.dataset.action==='importData')importData();if(b.dataset.action==='saveSettings'){db.settings={...db.settings,bizName:$('#sName').value,bizVat:$('#sVat').value,bizEmail:$('#sEmail').value,bizPhone:$('#sPhone').value,bizAddress:$('#sAddress').value,bankHolder:$('#sHolder').value,bank:$('#sBank').value,bankAccount:$('#sAccount').value,bankBranch:$('#sBranch').value,invPrefix:$('#sInvPrefix').value||'INV-',quotePrefix:$('#sQuotePrefix').value||'QUO-',vatRate:Number($('#sVatRate').value||0),thanks:$('#sThanks').value};save();toast('Settings saved')}
if(b.dataset.saveShow!==undefined){let id=b.dataset.saveShow,s=id?db.shows.find(x=>x.id===id):null,o={id:id||uid(),title:$('#fTitle').value,date:$('#fDate').value,venue:$('#fVenue').value,fee:Number($('#fFee').value||0),owner:$('#fOwner').value};s?Object.assign(s,o):db.shows.push(o);db.activity.unshift(`${o.title} saved`);closeModal();save();}
if(b.dataset.saveClient!==undefined){let id=b.dataset.saveClient,c=id?db.clients.find(x=>x.id===id):null,o={id:id||uid(),name:$('#cName').value,vat:$('#cVat').value,phone:$('#cPhone').value,email:$('#cEmail').value,address:$('#cAddress').value};c?Object.assign(c,o):db.clients.push(o);db.activity.unshift(`${o.name} saved`);closeModal();save()}
if(b.dataset.editShow)showForm(b.dataset.editShow);if(b.dataset.deleteShow){db.shows=db.shows.filter(x=>x.id!==b.dataset.deleteShow);save()}if(b.dataset.editClient)clientForm(b.dataset.editClient);if(b.dataset.deleteClient){db.clients=db.clients.filter(x=>x.id!==b.dataset.deleteClient);save()}if(b.dataset.editDoc){let [t,id]=b.dataset.editDoc.split(':');docForm(t,id)}if(b.dataset.deleteDoc){let [t,id]=b.dataset.deleteDoc.split(':');db[t+'s']=db[t+'s'].filter(x=>x.id!==id);save()}if(b.dataset.paid){let i=db.invoices.find(x=>x.id===b.dataset.paid);if(i){i.status='Paid';i.paidDate=today();db.activity.unshift(`${i.number} marked Paid`);save();toast(`${i.number} marked Paid`)}}if(b.dataset.convert){let q=db.quotes.find(x=>x.id===b.dataset.convert);if(q){db.invoices.push({...q,id:uid(),number:next('invoice'),status:'Unpaid',convertedFrom:q.number});q.status='Converted';db.activity.unshift(`${q.number} converted to invoice`);save();toast('Quote converted to invoice')}}if(b.dataset.printDoc){let [t,id]=b.dataset.printDoc.split(':');printDoc(t,id)}if(b.dataset.whats){let [t,id]=b.dataset.whats.split(':');let d=db[t+'s'].find(x=>x.id===id);let txt=`${t.toUpperCase()} ${d.number}\n${clientName(d.clientId)}\nTotal: ${money(d.total)}`;open('https://wa.me/?text='+encodeURIComponent(txt),'_blank')}if(b.dataset.saveMarketing!==undefined){db.marketing.push({name:$('#mName').value,date:$('#mDate').value,channel:$('#mChannel').value,status:$('#mStatus').value});db.activity.unshift(`${$('#mName').value||'Campaign'} saved`);closeModal();save();toast('Campaign saved')}if(b.dataset.deleteMarketing!==undefined){db.marketing.splice(Number(b.dataset.deleteMarketing),1);save();toast('Campaign deleted')}if(b.dataset.saveContract!==undefined){db.contracts.push({name:$('#ctName').value,client:$('#ctClient').value,date:$('#ctDate').value,status:$('#ctStatus').value});db.activity.unshift(`${$('#ctName').value||'Contract'} saved`);closeModal();save();toast('Contract saved')}if(b.dataset.deleteContract!==undefined){db.contracts.splice(Number(b.dataset.deleteContract),1);save();toast('Contract deleted')}if(b.dataset.addLine!==undefined){$('#lines').insertAdjacentHTML('beforeend',lineHtml());recalc()}if(b.dataset.removeLine!==undefined){b.parentElement.remove();recalc()}if(b.dataset.saveDoc){let [t,id]=b.dataset.saveDoc.split(':');saveDoc(t,id)}});
document.addEventListener('input',e=>{if(e.target.closest('#lines')||e.target.id==='dVat')recalc()});
$('#importFile').addEventListener('change',e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();toast('Backup imported')}catch{toast('Invalid ShowPay backup')}};r.readAsText(f)});
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
render();
