create table if not exists public.workspaces(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz default now());
create table if not exists public.workspace_members(workspace_id uuid references public.workspaces(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text default 'member',primary key(workspace_id,user_id));
create table if not exists public.clients(id uuid primary key default gen_random_uuid(),workspace_id uuid references public.workspaces(id) on delete cascade,name text not null,vat text,phone text,email text,address text,created_at timestamptz default now());
create table if not exists public.shows(id uuid primary key default gen_random_uuid(),workspace_id uuid references public.workspaces(id) on delete cascade,title text not null,date date,venue text,fee numeric default 0,owner text default 'Shared',created_at timestamptz default now());
create table if not exists public.documents(id uuid primary key default gen_random_uuid(),workspace_id uuid references public.workspaces(id) on delete cascade,kind text not null,number text not null,reference text,client_id uuid references public.clients(id),document_date date,due_date date,event_date date,payment_terms text,salesperson text,job text,subtotal numeric default 0,vat numeric default 0,vat_rate numeric default 0,total numeric default 0,status text default 'Unpaid',paid_date date,converted_from text,items jsonb default '[]',thanks text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists public.marketing(id uuid primary key default gen_random_uuid(),workspace_id uuid references public.workspaces(id) on delete cascade,name text,date date,channel text,note text);
create table if not exists public.contracts(id uuid primary key default gen_random_uuid(),workspace_id uuid references public.workspaces(id) on delete cascade,name text,client text,date date,file_path text);
alter table public.workspaces enable row level security; alter table public.workspace_members enable row level security; alter table public.clients enable row level security; alter table public.shows enable row level security; alter table public.documents enable row level security; alter table public.marketing enable row level security; alter table public.contracts enable row level security;
-- Add workspace-membership RLS policies before production use.
